use_frameworks!

platform :ios, '10.0'

target 'DragAndDropKit_Example' do
  pod 'DragAndDropKit', :path => '../'
  pod 'JFPopup', '~> 1.4.0'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 6.3.1'

  target 'DragAndDropKit_Tests' do
    inherit! :search_paths

    
  end
end
